### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by wf13MT** [ZenonSeth/logistica#13] opened 2024-04-15 23:26 UTC
Add a mode to the Bulk Item Requester and the Fast Network Importer to fill/empty the network completely.

Unrelated:

Are Networks able to be moved with the jumpdrive mod without issue?

**Comment by ZenonSeth** [comment] 2024-04-16 08:55
- **Fast Network Importer - fill network completely**: This is already possible, if you don't specify any type of item in the Importer's filter, it will try to import ALL items into the network, taking them from the chest/machine it's targeting.

- **Bulk Item Requester - empty network completely**: I had not considered that as a possible use case, but I can consider adding some mode to do this. More likely would be to add a mode to always demand a specific item from its filter list, rather than blindly take everything from network, but I will see.

- **Are Networks able to be moved with the jumpdrive mod without issue?**: Almost definitely not. I have not played that mod, but having a quick look, it would probably break the network. It may appear to work correctly for a little bit, but when you restart the game, it will most certainly break. Bottom line, Logistica machines and cables should not be moved around by other mods. Doing so will result in undefined and almost definitely wrong behavior, if not even crashes. 

  I MAY look into how that mod works, and try to add compatibility, but it depends on a lot of factors, and if there's too many issues, I may not add compatibility. You're better off waiting for the upcoming Wireless Network update to help you with setting up remote networks.

**Comment by ZenonSeth** [comment] 2024-04-20 20:27
@wf13MT Just so you are aware, I just published 1.1.0 that includes [Wireless Transmitters and Wireless Receivers](https://github.com/ZenonSeth/logistica/wiki/Logistic-Network:-Wireless-Network) that allow extending a network wirelessly.

**Comment by wf13MT** [comment] 2024-04-21 00:51
Thanks for looking into the jumpdrive compatibility issue and hope to see
the two mods compatible. The reason why I requested jumpdrive compatibility
is so you could use the mod in a jumpdrive base I am planning on building
in a singleplayer world, but because they are not compatible I will have to
find another way.

Anyways thanks for looking into it and hope to see the mods work together
soon. Thank you!

**Comment by wf13MT** [comment] 2024-04-21 01:23
Also after testing out the new wireless block, you should be able to access
the system even if the synced access point is too far away if you are in
rang of another access point connected to the synced access point.

**Comment by wf13MT** [comment] 2024-04-21 03:53
I should say "connected to the synced access point" via the wireless blocks

**Comment by ZenonSeth** [comment] 2024-04-21 10:09
@wf13MT What you describe IS actually possible - you can connect to a Wireless Transmitter from **anywhere** on the map. The only thing is that, especially if you play singleplayer, a network is not "awake"/"active" right after a server restart (or in singleplayer case, after starting the game) UNTIL you go near its controller. You can now right click the controller to force it to rescan the network and thus make it active.

There are some ways to "wake up" a network remotely if there's a receiver or access point already connected to it - but there was a minor bug in 1.1.0 which is now fixed in 1.1.1 - that may have prevented that from fully working.

In either case, on singleplayer, it's still easiest to just go near the Network Controller to wake up the network, after which you should be able to connect to it from anywhere on the map, until the next game shutdown/restart.

**Comment by wf13MT** [comment] 2024-04-21 23:54
I have done that but it did not work

**Comment by ZenonSeth** [comment] 2024-04-22 00:03
Have you tried with version 1.1.2 ? It fixes a few network related things. 

If you still can't get it to work, then please let me know what your setup roughly looks like and I will try to reproduce the issue locally.

**Comment by wf13MT** [comment] 2024-04-25 22:44
ok thanks!

**Comment by wf13MT** [comment] 2024-04-25 22:45
Also how is the jumpdrive compatibility going?

**Comment by ZenonSeth** [comment] 2024-04-26 18:17
I'm extremely busy with other things in real life, I haven't worked on jumpdrive compatibility. I had a look at their API, it should be possible, but I will need to actually sit down and try it. At the earliest, I will work on it next week - if I have time.

**Comment by wf13MT** [comment] 2024-05-03 00:58
ok thank you so much as some other serves would like to add your mod with
the jumpdrives, but you should focus on real life first and foremost, thank
you again for creating such a great mod!

**Comment by wf13MT** [comment] 2024-05-03 00:59
Ok thank you so much as some other server would like to add your mod with
the jumpdrives, but you should focus on real life first and foremost, thank
you again for creating such a great mod!

**Comment by KAnon20** [comment] 2024-07-24 03:26
ZenonSeth: "Bulk Item Requester - empty network completely: I had not considered that as a possible use case,"
Yes.. After I accidentally filled my 4k network on single player, I had to overcome it and chose to create mutliple networks and dump everything form each network into the storage network after. The problem being that there was no way to "send everything to a chest and import into the primary network (ie: Chest > Importer+Wireless).

After updating from 1.19? or 1.20 to current, an issue occurred. It might be related to #20 but some of my Inserters taking items from network to Chest to Importer+Wireless suddenly stopped working. I had 4 items listed and unless I tweaked them, the mob farm I set up wouldn't send items and was thinking I needed 1 Inserter+Barrel+Exporter per item (but if it's related to #20 duping that changed, that could be the cause.

A Network-tranfer fix for the Inserter seems like a great idea to me.

**Comment by ZenonSeth** [comment] 2024-07-24 22:05
The Infinite Requesting capabilities of the Request Inserter are now implemented in [Release 1.2.5](https://github.com/ZenonSeth/logistica/releases/tag/1.2.5) - also available on ContentDB. 

The in-game guidebook has been updated too, and will update online guide later.

**Comment by wf13MT** [comment] 2024-08-08 04:16
Thanks! Also how is the Jumpdrive mod compatibility going?

**Comment by ZenonSeth** [comment] 2024-08-08 17:13
I started the work and had a branch, but the wireless transmitters specifically were giving me lots of trouble and I didn't have time to test them further to fix it. I'll plan some time this weekend to get to it and hopefully get it done by end of next week.

**Comment by wf13MT** [comment] 2024-08-25 04:17
Awesome, thanks for the update!

**Closed** 2024-12-24 17:36 UTC
Labels: enhancement
