### ISSUE TITLE
Crafting Supplier infinite loop

### ISSUE THREAD

**Issue by Maverick2797** [ZenonSeth/logistica#6] opened 2024-01-12 03:43 UTC
I haven't looked through the source, but having a crafting supplier making steel blocks from ingots, and another making steel ingots out of blocks causes the MT engine to hang if you try to take more than what's in storage. I suspect an infinite recursion loop as there's nothing logged in the debug.txt when I force close the program.

**Comment by ZenonSeth** [comment] 2024-01-12 15:43
There are actually specific checks which I have put in, and have tested and verified that they work - in [this commit](https://github.com/ZenonSeth/logistica/commit/680bdae75258a5690c6a2c616b84ee407917b266) a couple of months ago - to prevent exactly that kind of infinite recursion scenario due to crafters using each other in a loop. The cause would have to be something else, if you were using it via an Access Point it may be related to that.

I would have to reproduce this issue to tell for certain, but as mentioned, it's likely not circular crafting supplier usage.

**Comment by ZenonSeth** [comment] 2024-01-13 15:15
I've attempted to reproduce this on the latest release 0.9.4/0.9.5 - and cannot. The depth check I linked to above prevents infinite loops from happening, even when used from an Access Point - so if you run into this issue again, I would appreciate some sort of steps to reproduce, otherwise I don't know what needs fixing.

**Comment by ZenonSeth** [comment] 2024-03-17 20:13
I've recently updated the supply crafters, fixing another bug that was reported - and in doing so I did a lot of testing of supply crafters. I cannot reproduce this issue - if you set up a lot of supply crafters that use each other, it's possible to get a slight lag, but they don't actually cause a freeze.

I'm closing this bug for now - if you encounter it again, I would greatly appreciate some steps, and maybe a picture of your setup, so I can try to see what could be causing this - but I suspect the bug is no longer present.

**Closed by ZenonSeth** 2024-03-17 20:13 UTC
Labels: bug
